### ISSUE TITLE
Unread message hilighting

### ISSUE THREAD

**Issue by bbenne10** [laochailan/barely#3]
Moved discussions from #1 to keep that feature specific. 

I'm currently implementing line based hilighting for an "unread" tag. A framework for this is currently implemented [here](https://github.com/bbenne10/barely/tree/hilight_unread). (Note that this doesn't work currently. I suspect it's due to a mismatch in types between `UnreadTag` and `tag` in the  implementation but I've not checked that yet)

This is the simplest implementation I can think of that hilights the entire line. I wouldn't mind an implementation that only colors the tag, but that would be significantly more code overall, though I prefer the line highlight. I'm not sure that it'd be completely worth the overhead, but it may very well be.

**Comment by laochailan** [comment]
I put together arbitrary tag highlighting [here](https://github.com/laochailan/barely/commit/efaaea4019b79594529034befdc32aa20a36dabb). What do you think?

It took 8 lines more than your implementation, so there is a bit of overhead, but since it’s a very general feature, I think it is worth it.

**Comment by bbenne10** [comment]
Looks good to me. 8 lines means very little, seeing as this works and my implementation would need some more work to come close.

**Comment by laochailan** [comment]
Okay, then I’ll merge this into master. I hope it doesn’t conflict too badly with your column code.
